### ISSUE TITLE
[ModernX] show osc on "start-file" and "seek"

### ISSUE THREAD

**Issue by pintassilgo** [dexeonify/mpv-config#4]
Hi,

First of all, thanks for sharing your work.

I added two lines at the end of the script to get two features I wanted. Just reporting here for you to think about if it would be useful to present them as user options.

**1.** In your script, theres no indicator when the next file starts playing (in playlist). I want `osc` to be be temporarily visible (by the time set in `hidetimeout`). This line does the job:
```lua
mp.register_event("start-file", show_osc)
```

**2.** By default, `osd-bar` is displayed when you seek (like when you press `→` key). I prefer to hide it with `no-osd-bar` in `mpv.conf` and to display `osc` instead.
```lua
mp.register_event("seek", show_osc)
```

**Comment by dexeonify** [comment]
Hmm, I don't plan to add these because I don't want the OSC to obstruct anything I do. However, I appreciate you for sharing the code. I suggest sharing your findings to [upstream](https://github.com/cyl0/MordenX) for more coverage.

Since my main goal is to mirror mpv's own osc.lua as closely as possible, I'm pretty adamant in adding substantial features. It's why I haven't got around to add MordenX's directional keyboard feature.

**Comment by dexeonify** [comment]
Actually, change my mind. This is a pretty small feature to add so it shouldn't diverge too much from osc.lua 👍
